# moonlight-ps4
# Edit host / debug_host on-console (Settings menu) or here after install.
host =
app = Desktop
debug_host =
width = 1920
height = 1080
fps = 60
bitrate = 20000
sops = true
local_audio = false
prefer_hw = true
videodec2_spike = false
prefer_ycbcr = false
enable_file_log = false
